/**
 * Canonical: docs/technical/dapp-browser-keygen-review.md
 *
 * Browser-generated agent credential path (Phase 6).
 *
 * Security model (from ADR §4):
 *   - Private key lives only in JavaScript heap during the generation session.
 *   - Never written to localStorage, sessionStorage, or indexedDB.
 *   - Never sent over the network.
 *   - Never passed to console.log / console.debug / analytics.
 *   - Cleared from memory after the user confirms the key has been copied.
 *   - Only the derived public address is retained for on-chain registration.
 *
 * Entropy source (from ADR §3): window.crypto.getRandomValues (CSPRNG).
 *
 * Export format (from ADR §5): plain-hex private key with
 * unsafe_for_production = true in a rmpc-compatible TOML fragment.
 *
 * IMPORTANT: This module must only be imported when isBrowserKeygenAvailable()
 * returns true (i.e. DAPP_BROWSER_KEYGEN_ENABLED=true AND chain is not
 * production). See src/config.ts.
 */

import { isDevnetChain } from "./config.js";

/** Result of a browser keygen session. */
export interface KeygenResult {
  /** The agent's public Ethereum address (hex, 0x-prefixed). Retained for on-chain use. */
  address: string;
  /** The rmpc-compatible TOML config fragment. Contains unsafe_for_production = true. */
  tomlConfig: string;
  /** Suggested filename for the exported config. Includes -DEVNET-UNSAFE suffix per ADR §5. */
  filename: string;
}

/**
 * Generate a new ECDSA keypair using the browser CSPRNG, derive the Ethereum
 * address, and produce an rmpc-compatible TOML config fragment.
 *
 * The private key is returned ONLY inside the `tomlConfig` string. Callers
 * must display it once, wait for user confirmation, and then clear the
 * returned object from scope (set to null).
 *
 * @param chainId - The devnet/fork chain id (must not be a production chain).
 * @param rpcUrl  - The devnet RPC URL to embed in the config.
 * @throws {Error} if called with a production chain id, or if the Web Crypto
 *   API is unavailable.
 */
export async function generateBrowserCredential(
  chainId: bigint,
  rpcUrl: string,
): Promise<KeygenResult> {
  // Runtime guard: refuse production chains even if the build-time flag is set.
  // This mirrors the rmpc guard in clients/rust-payment-client/src/commands/self_check.rs.
  if (!isDevnetChain(chainId)) {
    throw new Error(
      `[keygen] refused: chain_id=${chainId} is a production chain. ` +
      `Browser-generated credentials are fork/devnet only.`,
    );
  }

  if (!window.crypto?.getRandomValues) {
    throw new Error("[keygen] Web Crypto API (getRandomValues) is unavailable.");
  }

  // Generate 32 bytes of cryptographically random entropy via the OS CSPRNG
  // (ADR §3: window.crypto.getRandomValues draws from Linux getrandom(2) /
  // macOS CCRandomGenerateBytes / Windows BCryptGenRandom).
  const privateKeyBytes = new Uint8Array(32);
  window.crypto.getRandomValues(privateKeyBytes);

  // Derive the Ethereum address from the private key.
  // We use the ethers library's Wallet abstraction which performs the
  // secp256k1 public key derivation and keccak256 address derivation.
  // ethers v6 Wallet requires a 0x-prefixed hex string, not a Uint8Array.
  const { ethers } = await import("ethers");
  const privateKeyHexForWallet =
    "0x" + Array.from(privateKeyBytes).map((b) => b.toString(16).padStart(2, "0")).join("");
  const wallet = new ethers.Wallet(privateKeyHexForWallet);

  // NOTE: privateKeyBytes is a Uint8Array on the heap. We will zero it after
  // building the TOML so the raw bytes do not linger in memory longer than
  // necessary. The hex representation in `tomlConfig` is the intended
  // disclosure channel.
  const privateKeyHex = wallet.privateKey; // "0x" + 64 hex chars
  const address = wallet.address;          // "0x" + 40 hex chars (checksummed)

  const tomlConfig = buildTomlConfig(privateKeyHex, chainId, rpcUrl);
  const filename = buildFilename(address);

  // Zero the raw private key bytes now that we have the hex representation
  // in the TOML. This reduces (but does not eliminate) the residual
  // window during which the key occupies heap memory.
  privateKeyBytes.fill(0);

  return { address, tomlConfig, filename };
}

/**
 * Build the rmpc-compatible TOML config fragment per ADR §5.
 *
 * The fragment includes:
 *   - A header comment explaining the source and risk.
 *   - [signer] with unsafe_for_production = true.
 *   - [network] with the chain_id and rpc_url.
 *
 * SECURITY: This function receives the private key hex string. It MUST NOT:
 *   - Pass `privateKeyHex` to any logging function.
 *   - Store `privateKeyHex` in any persistent storage.
 *   - Include `privateKeyHex` in any network request body.
 */
function buildTomlConfig(
  privateKeyHex: string,
  chainId: bigint,
  rpcUrl: string,
): string {
  return [
    "# GENERATED BY DAPP BROWSER KEYGEN — FORK/DEVNET ONLY",
    "# unsafe_for_production = true",
    "# This key was generated in a browser session. It is not hardware-backed.",
    "# Use only against fork and devnet environments.",
    "# rmpc self-check will refuse to start against any production chain id.",
    "",
    "[signer]",
    'type = "local_key"',
    `private_key = "${privateKeyHex}"`,
    "unsafe_for_production = true",
    "",
    "[network]",
    `chain_id = ${chainId}`,
    `rpc_url = "${rpcUrl}"`,
    "",
  ].join("\n");
}

/**
 * Returns the suggested export filename per ADR §5.
 * Must include the `-DEVNET-UNSAFE` suffix.
 */
function buildFilename(address: string): string {
  const shortAddr = address.slice(0, 10).toLowerCase();
  return `rmpc-agent-config-${shortAddr}-DEVNET-UNSAFE.toml`;
}

/**
 * Clear a KeygenResult from memory by overwriting all string fields.
 *
 * Callers should invoke this after the user has confirmed the key has been
 * copied. Note: JavaScript strings are immutable — this replaces the
 * references in the object; it cannot zero the underlying string buffers.
 * The GC will eventually reclaim those. This is the best available
 * mitigation in the browser JS environment.
 *
 * After calling this, `result.tomlConfig` and `result.filename` will be
 * empty strings.
 */
export function clearKeygenResult(result: KeygenResult): void {
  (result as { tomlConfig: string }).tomlConfig = "";
  (result as { filename: string }).filename = "";
  // address is intentionally retained — it is the public value used for
  // on-chain registration and is not a secret.
}
